### PR TITLE
Remove hash from div id

### PR DESCRIPTION
**Pull request by mbolli**
In the id attribute the hash is not allowed.

### CODE REVIEW

**Comment by mbolli** [comment]
Hi @RamyRais could you create a new release with this fix? In Chrome the progress bar only works after applying this fix – the npm users would be grateful.

**Comment by RamyRais** [comment]
thank you for reminding me. I will do it this week ;)

**Comment by RamyRais** [comment]
@mbolli it is done. thx for your pull request.

**Comment by mbolli** [comment]
Hey @RamyRais, I can't see the new release, can you check it please?

**Comment by RamyRais** [comment]
hey @mbolli, it should be there as the new version 0.3.3 published in NPM.
https://www.npmjs.com/package/multi-nprogress

**Comment by mbolli** [comment]
Weird, now I see it (in github as well), before the most recent one was 0.3.2. Anyway thanks!

**Pull request merged**
